services:
  message-client:
    image: ${GHCR_IMAGE_URL}/client:latest
    networks:
      - message-app
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PORT=${PORT}

  message-api:
    image: ${GHCR_IMAGE_URL}/api:latest
    networks:
      - message-app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      message-db:
        condition: service_healthy

  message-db:
    image: ${GHCR_IMAGE_URL}/db:latest
    networks:
      - message-app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${PGPORT}
    volumes:
      - message_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -p ${PGPORT} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  proxy:
    external: true
  message-app:
    driver: bridge

volumes:
  message_db_data:
    external: true