FROM python:3.12-slim

ENV TZ=Asia/Seoul

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN addgroup --system python && \
  adduser --system --ingroup python fastapi && \
  chown -R fastapi:python /app

USER fastapi

EXPOSE 8008

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8008"]
