name: Build - DB

on:
  push:
    branches:
      - main
    paths:
      - db/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          context: db
          image_name: message/db
          REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          image_tag: 2024-2025
