name: Build - Client

on:
  push:
    branches:
      - main
    paths:
      - client/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create environment variables
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> ./client/.env.local
          echo "PORT=3343" >> ./client/.env.local

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          context: client
          image_name: message/client
          REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          image_tag: 2024-2025

      - name: Remove environment variables
        run: |
          rm -f ./client/.env.local
